import { NextRequest, NextResponse } from "next/server";
import { getSessionFromRequest } from "@/lib/auth";
import { z } from "zod";

const suggestSchema = z.object({
  prompt: z.string().min(3, "Tell me a bit more about what you want to battle over.").max(200),
});

interface BattleSuggestion {
  title: string;
  topic: string;
  sideA: string;
  sideB: string;
}

const SYSTEM_PROMPT = `You are the Ragebait Battle Creator Assistant. A user gives you a rough idea for
a roast/debate battle and you turn it into a punchy, ready-to-use battle setup.

Rules:
- "title" is a catchy battle title, under 70 characters.
- "topic" is a short topic label, under 60 characters (this is what shows on the battle card).
- "sideA" and "sideB" are one-sentence opening stances for each side of the debate, written to
  bait maximum engagement while staying free of slurs, hate speech, harassment, or targeting of
  real private individuals.
- Keep it fun and a little spicy, never actually hateful or dangerous.

Return ONLY valid JSON, no markdown, in exactly this shape:
{"title": "", "topic": "", "sideA": "", "sideB": ""}`;

// POST /api/battles/suggest — AI helper that turns a rough idea into a battle setup.
// Does not create a battle; the client still submits the final fields through POST /api/battles.
export async function POST(req: NextRequest) {
  const session = await getSessionFromRequest(req);
  if (!session) {
    return NextResponse.json({ error: "Not authenticated." }, { status: 401 });
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  }

  const parsed = suggestSchema.safeParse(body);
  if (!parsed.success) {
    const firstError = parsed.error.issues[0];
    return NextResponse.json({ error: firstError?.message ?? "Invalid input." }, { status: 400 });
  }

  if (!process.env.OPENAI_API_KEY) {
    return NextResponse.json({
      suggestion: fallbackSuggestion(parsed.data.prompt),
      note: "Generated by the built-in assistant (no OpenAI key configured).",
    });
  }

  try {
    const suggestion = await runSuggestionModel(parsed.data.prompt);
    return NextResponse.json({ suggestion });
  } catch (err) {
    console.error("Battle suggestion error:", err);
    // Never block battle creation just because the assistant failed —
    // fall back to a deterministic suggestion instead of a hard error.
    return NextResponse.json({
      suggestion: fallbackSuggestion(parsed.data.prompt),
      note: "AI assistant was unavailable, showing a basic suggestion instead.",
    });
  }
}

async function runSuggestionModel(prompt: string): Promise<BattleSuggestion> {
  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: `Idea: ${prompt}` },
      ],
      temperature: 0.9,
      response_format: { type: "json_object" },
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`OpenAI API error: ${response.status} ${errText}`);
  }

  const data = await response.json();
  const raw = data.choices?.[0]?.message?.content;
  if (!raw) {
    throw new Error("Battle assistant returned an empty response.");
  }

  let parsed: BattleSuggestion;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("Battle assistant returned invalid JSON.");
  }

  if (!parsed.title || !parsed.topic || !parsed.sideA || !parsed.sideB) {
    throw new Error("Battle assistant returned an incomplete suggestion.");
  }

  return {
    title: parsed.title.slice(0, 140),
    topic: parsed.topic.slice(0, 60),
    sideA: parsed.sideA.slice(0, 280),
    sideB: parsed.sideB.slice(0, 280),
  };
}

/** Deterministic fallback used when no OpenAI key is configured or the API call fails. */
function fallbackSuggestion(prompt: string): BattleSuggestion {
  const cleaned = prompt.trim().replace(/\s+/g, " ");
  const topic = cleaned.length > 60 ? cleaned.slice(0, 57) + "..." : cleaned || "Open Debate";
  return {
    title: `${topic}: Who Actually Wins?`,
    topic,
    sideA: `Team A: ${cleaned || "This side"} is obviously correct — everyone else is coping.`,
    sideB: `Team B: ${cleaned || "The other side"} has been wrong this whole time, and it's not close.`,
  };
}
